### ISSUE TITLE
TBA APIv3 - Failure reading key after downloading

### ISSUE THREAD

**Issue by noahhusby** [tweirtx/ReMatch#5]
Got this error after downloading files. I have tbakey.txt configured using my custom TBA key.

The error is as follows:

`Traceback (most recent call last):
  File "C:\Users\Noah Husby\Desktop\ReMatch-master\ReMatch\TBA.py", line 20, in DB_setup
    time = match['actual_time'] + libtime.altzone
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\site-packages\tbapi\v3\models.py", line 121, in __getitem__
    return self.__get_data_value(key)
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\site-packages\tbapi\v3\models.py", line 100, in __get_data_value
    raise InvalidKeyError
tbapi.v3.exceptions.InvalidKeyError: Data Key does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Noah Husby\Desktop\ReMatch-master\ReMatch\__main__.py", line 52, in <module>
    main_rewrite(args['event_key'], args['event_type'], args['video_id_day_one'], args['video_type_day_one'], args['video_id_day_two'], args['video_type_day_two'], args['video_id_day_three'], args['video_type_day_three'])
  File "C:\Users\Noah Husby\Desktop\ReMatch-master\ReMatch\__main__.py", line 33, in main_rewrite
    TBA.DB_setup(TBA(), event_key, day_one_timestamp, day_two_timestamp, day_three_timestamp, "frc")
  File "C:\Users\Noah Husby\Desktop\ReMatch-master\ReMatch\TBA.py", line 22, in DB_setup
    print("An error occurred when getting the match time for", match['key'])
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\site-packages\tbapi\v3\models.py", line 121, in __getitem__
    return self.__get_data_value(key)
  File "C:\Users\Noah Husby\AppData\Local\Programs\Python\Python37\lib\site-packages\tbapi\v3\models.py", line 100, in __get_data_value
    raise InvalidKeyError
tbapi.v3.exceptions.InvalidKeyError: Data Key does not exist`

**Comment by noahhusby** [comment]
Turns out it couldn't find the event. The event name is case sensitive. Its working great now.
